name: ドキュメント改善（誤字/表現/図/リンク）
description: 本文の修正・追記・図の差し替えなどを提案します
title: "[Docs] "
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        変更対象のページ（URL/ファイル）と、修正理由が分かると対応が早くなります。

  - type: input
    id: target
    attributes:
      label: 対象ページ（URL or ファイルパス）
      placeholder: 例）https://itdojp.github.io/github-guide-for-beginners-book/src/chapter-issue-management/  または  manuscript/chapter-issue-management/index.md
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 現状（問題点）
      placeholder: 例）用語が未定義 / UI表現が古い / リンク切れ など
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: 改善案（どう直したいか）
      placeholder: 例）初出で用語定義を追加 / 公式ドキュメントへの参照に寄せる など
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 受入基準（DoD）
      description: 変更が完了したと判断できる条件を、チェック可能な形で箇条書きにしてください
      placeholder: |
        - [ ] （例）誤字が修正されている
        - [ ] （例）リンク先が有効で、意図したページに到達する
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: 制約・変更禁止領域（任意）
      description: 触ってはいけないファイル/設定や、変更方針の制約があれば明記してください
      placeholder: |
        - 変更してよい:
        - 変更してはいけない:
    validations:
      required: false

  - type: textarea
    id: test
    attributes:
      label: テスト方法（任意）
      description: 最低限の確認コマンドや手動確認手順（例：CI/リンク確認）を書いてください
      placeholder: |
        - コマンド:
        - 手動確認:
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 補足（任意）
      description: スクリーンショット、関連Issue/PR、参考リンクなど
    validations:
      required: false
